services:
  spark:
    image: jupyter/pyspark-notebook:latest
    container_name: spark-ml-container
    ports:
      - "8080:8080"    # Jupyter
      - "4040:4040"    # Spark Application UI
    volumes:
      - ./app:/home/jovyan/app
    stdin_open: true
    tty: true
    command: /bin/bash
